# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hook
repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort
-   repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
    - id: black
      language_version: python3.8
